### ISSUE TITLE
No need for this plugin

### ISSUE THREAD

**Issue by Thermisen75** [stassop/highlite#1]
Did you made a research before implementing this? There's already a plugin for that: [jquery.mark](https://github.com/julmot/jquery.mark)

**Comment by stassop** [comment]
Sure. You must have missed the “lite” part :) It would still suffice in 99%
of usecases. Overengineering things is rarely justified.

**Comment by Thermisen75** [comment]
If this is your only argument, why aren't you using the simple [highlighting](http://johannburkard.de/blog/programming/javascript/highlight-javascript-text-higlighting-jquery-plugin.html) plugin without any options?

**Comment by stassop** [comment]
Because I don't like it. And you're free not to use mine. However,
complaining about there being “one too many” is counter to what evolution
(and Github) is about: variety drives progress.

**Comment by Thermisen75** [comment]
@stassop Sorry, but evolution starts with advancing improvements. This plugin is a step back as it brings up issues that were already solved in different plugins (like the [mark.js](https://github.com/julmot/mark.js) or [highlight](http://johannburkard.de/blog/programming/javascript/highlight-javascript-text-higlighting-jquery-plugin.html) plugin). From my point of view there is no reason why someone should choose this plugin because it does not improve anything.
